#pragma once

#include <string>
#include <unordered_map>

#include "cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT, BOOL}},
    {"DisableUpdates", {PERSISTENT, BOOL}},
    {"DisengageOnAccelerator", {PERSISTENT, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"AlphaLongitudinalEnabled", {PERSISTENT | DEVELOPMENT_ONLY, BOOL}},
    {"ExperimentalMode", {PERSISTENT, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"PowerSaverEntryDuration", {PERSISTENT, INT, "30"}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT, STRING}},
    {"GithubUsername", {PERSISTENT, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT, STRING}},
    {"GsmMetered", {PERSISTENT, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT, BOOL}},
    {"IsMetric", {PERSISTENT, BOOL}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsOnroad", {PERSISTENT, BOOL}},
    {"QuietMode", {PERSISTENT, BOOL, "0"}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTakingSnapshot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LanguageSetting", {PERSISTENT, STRING, "main_en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"LiveDelay", {PERSISTENT, BYTES}},
    {"LiveParameters", {PERSISTENT, JSON}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_IsTakingSnapshot", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_StorageMissing", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSomResetTriggered", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSignatures", {CLEAR_ON_MANAGER_START, BYTES}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT, BOOL}},
    {"RecordAudioFeedback", {PERSISTENT, BOOL, "0"}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG, STRING}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT, BOOL}},
    {"TermsVersion", {PERSISTENT, STRING}},
    {"TrainingVersion", {PERSISTENT, STRING}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdateStatus", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"Version", {PERSISTENT, STRING}},

    // ---- EOP keys (RK3588 port + EOP features) ----
    {"BluetoothPairingActive", {CLEAR_ON_MANAGER_START, STRING, "0"}},
    {"BluetoothPairingAddr", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"BluetoothPairingPin", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"CameraCalibrationParams", {PERSISTENT, BYTES}},
    {"EOPAEBEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPALCCAllowAlways", {PERSISTENT, BOOL, "0"}},
    {"EOPALCCBrakeMode", {PERSISTENT, STRING, "Maintain"}},
    {"EOPALCCHoldAtStandstill", {PERSISTENT, BOOL, "0"}},
    {"EOPALCCSteeringModeOnBrake", {PERSISTENT, INT, "1"}},
    {"EOPALCCUnifiedEngagement", {PERSISTENT, BOOL, "0"}},
    {"EOPAccelerationProfile", {PERSISTENT, STRING, "normal"}},
    {"EOPAdaptdEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPAdaptiveGapEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPAggressiveFollow", {PERSISTENT, FLOAT, "1.25"}},
    {"EOPAggressiveJerk", {PERSISTENT, FLOAT, "0.5"}},
    {"EOPAutoLaneChange", {PERSISTENT, BOOL, "0"}},
    {"EOPAutoTileEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPAutoTileWifiOnly", {PERSISTENT, BOOL, "1"}},
    {"EOPBEVWidgetEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPBSDChimeEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPBSDEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPBSDMinSpeed", {PERSISTENT, FLOAT, "5.5"}},
    {"EOPBluetoothCANInterface", {PERSISTENT, STRING, "can0"}},
    {"EOPBluetoothEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPBluetoothPairWindow", {PERSISTENT, INT, "300"}},
    {"EOPBluetoothRadarEnabled", {PERSISTENT, BOOL, "0"}},
    {"BLECornerPairs", {PERSISTENT, STRING, ""}},
    {"BLERadarPairingOpen", {PERSISTENT, BOOL, "0"}},
    {"EOPCATEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPCATManualSR", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPCATManualSREnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPCATPersist", {PERSISTENT, STRING, ""}},
    {"EOPCurrentRegion", {PERSISTENT, STRING, ""}},
    {"EOPCurveSpeedDBPath", {PERSISTENT, STRING, "/data/shared/exopilot/curve.db"}},
    {"EOPCurveSpeedLearnEnabled", {PERSISTENT, BOOL, "1"}},
    // DLAT (Dynamic Lateral Profile, dlat.py) is a default, always-on
    // automatic Laneful/Laneless arbitration -- no user-selectable mode
    // param, matching dev/NGP10's design.
    {"EOPDLONCurvesEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLONForceStopsEnabled", {PERSISTENT, BOOL, "1"}},
    // Couples DLAT's own Laneful/Laneless arbitration (dlat.py) into DLON's
    // automatic switch: when DLAT has committed to Laneless, E2E's path-only
    // prediction fits better than lane-line-anchored ACC.
    {"EOPDLONLaneConfidenceEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLONLowSpeedEnabled", {PERSISTENT, BOOL, "1"}},
    // DLON (Dynamic Longitudinal Profile) is a default, always-on automatic
    // ACC/E2E switch -- no mode param: users cannot force pure E2E
    // (Experimental) or pure ACC directly, matching dev/NGP10's design.
    {"EOPDLONNavigationEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLONSignalEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLONSlowLeadEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLONSpeedLimitEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLONStopPredictionEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLPCurvesEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDeviceAudibleAlertMode", {PERSISTENT, STRING, "Std"}},
    {"EOPDeviceAutoShutdownIn", {PERSISTENT, INT, "0"}},
    {"EOPDeviceBeep", {PERSISTENT, BOOL, "1"}},
    {"EOPDeviceGoOffRoad", {PERSISTENT, BOOL, "0"}},
    {"EOPDeviceIsRhd", {PERSISTENT, BOOL, "0"}},
    {"EOPDeviceModelList", {PERSISTENT, STRING, ""}},
    {"EOPDeviceModelSelected", {PERSISTENT, STRING, ""}},
    {"EOPDeviceName", {PERSISTENT, STRING, "EXOPILOT"}},
    {"EOPFactoryCalibrated", {PERSISTENT, BOOL, "0"}},
    {"EOPFeatureAdvancedAnalytics", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureAiRouting", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureCloudBackup", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureCrossDeviceSync", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureDrivingScore", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureEmergencyAlert", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureFleetMode", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureLiveLocationShare", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureLiveTraffic", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureObdDashboard", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeaturePriorityTiles", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureRemoteCamera", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureRouteReplay", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureTelemetry", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureTripSync", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFollowingDistance", {PERSISTENT, STRING, "normal"}},
    {"EOPGlobaldEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPGridEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPGroundEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPHealthMonitorEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPHybridPlannerEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPIgnitionOn", {CLEAR_ON_MANAGER_START, BOOL, "1"}},
    {"EOPLCABSMEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPLCAConfirmRequired", {PERSISTENT, BOOL, "1"}},
    {"EOPLCAControllerEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPLCAGapEvalEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPLCALaneWidthEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPLCASurroundOverride", {PERSISTENT, BOOL, "0"}},
    {"EOPLCAdjacentLeadHandoff", {PERSISTENT, BOOL, "0"}},
    {"EOPLaneChangeDelay", {PERSISTENT, FLOAT, "1.0"}},
    {"EOPLanguage", {PERSISTENT, STRING, "en"}},
    {"EOPLatALCC", {PERSISTENT, BOOL, "1"}},
    {"EOPLatLCASpeed", {PERSISTENT, INT, "0"}},
    {"EOPLatRoadEdgeDetection", {PERSISTENT, BOOL, "1"}},
    {"EOPLeftCameraEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPLonExtRadar", {PERSISTENT, BOOL, "0"}},
    {"EOPMSLCAlert", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPMSLCEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPMSLCOffsetFixed", {PERSISTENT, INT, "0"}},
    {"EOPMSLCOffsetPercent", {PERSISTENT, INT, "0"}},
    {"EOPMTSCEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPMapdEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPMicAdaptiveLoudness", {PERSISTENT, BOOL, "1"}},
    {"EOPMinimumLaneWidth", {PERSISTENT, FLOAT, "3.0"}},
    {"EOPMonoDEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPMonoDMaxTracks", {PERSISTENT, INT, "64"}},
    {"EOPMonoDSceneSegEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPMonoDWideEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPMonoDYoloConf", {PERSISTENT, FLOAT, "0.5"}},
    {"EOPMultiCameraCalibEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPNSLCEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPNavBleEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPNavEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPNavPilotAddress", {PERSISTENT, STRING, ""}},
    {"EOPNavPilotPaired", {PERSISTENT, BOOL, "0"}},
    {"EOPNavVoiceEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPNudgeEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPOneLaneChange", {PERSISTENT, BOOL, "0"}},
    {"EOPOsmLocalizerEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPParkingMode", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPPointcloudEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPPointcloudMaxGB", {PERSISTENT, FLOAT, "4.0"}},
    {"EOPPointcloudRateHz", {PERSISTENT, INT, "5"}},
    {"EOPPointcloudUseGPU", {PERSISTENT, BOOL, "1"}},
    {"EOPPredictEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPRCDEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPRearCameraEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPRearEGPUMode", {PERSISTENT, STRING, "off"}},
    {"EOPRearSegEGPUMode", {PERSISTENT, STRING, "off"}},
    {"EOPRearCameraHeight", {PERSISTENT, INT, "480"}},
    {"EOPRearCameraWidth", {PERSISTENT, INT, "640"}},
    {"EOPRecordEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPRecordSnap", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPRecorddImpactSensitivity", {PERSISTENT, INT, "50"}},
    {"EOPRecorddParkingEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPRecorddParkingHours", {PERSISTENT, FLOAT, "12.0"}},
    {"EOPRecorddPostBufferSec", {PERSISTENT, FLOAT, "30.0"}},
    {"EOPRecorddPreBufferSec", {PERSISTENT, FLOAT, "10.0"}},
    {"EOPRecorddQuality", {PERSISTENT, STRING, "medium"}},
    {"EOPRecorddSnapAutoG", {PERSISTENT, FLOAT, "2.0"}},
    {"EOPRecorddSnapImuMs", {PERSISTENT, INT, "500"}},
    {"EOPRedControllerEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPRelaxedFollow", {PERSISTENT, FLOAT, "1.75"}},
    {"EOPRelaxedJerk", {PERSISTENT, FLOAT, "1.0"}},
    {"EOPRightCameraEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPRoadHDR", {PERSISTENT, STRING, "hdr4"}},
    {"EOPSGMConfidenceThreshold", {PERSISTENT, FLOAT, "0.7"}},
    {"EOPSGMLocalizerEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPSGMMapPath", {PERSISTENT, STRING, "/data/maps/sgm"}},
    {"EOPSGMMaxRange", {PERSISTENT, FLOAT, "100.0"}},
    {"EOPSGMMode", {PERSISTENT, STRING, "live"}},
    {"EOPSLCConfirmHigher", {PERSISTENT, BOOL, "1"}},
    {"EOPSLCConfirmLower", {PERSISTENT, BOOL, "1"}},
    {"EOPSLCOffset1", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSLCOffset2", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSLCOffset3", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSLCOffset4", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSLCOffset5", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSLCOffset6", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSLCOffset7", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSOCControllerEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPSPPAutoReconnect", {PERSISTENT, BOOL, "1"}},
    {"EOPSPPChannel", {PERSISTENT, INT, "1"}},
    {"EOPSPPDeviceName", {PERSISTENT, STRING, ""}},
    {"EOPSPPEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPSPPMaxClients", {PERSISTENT, INT, "3"}},
    {"EOPSPPPairedDevice", {PERSISTENT, STRING, ""}},
    {"EOPSPPRpcRequest", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPSPPRpcResponse", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPSQSCEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPSQSCLookaheadEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPSQSCProfile", {PERSISTENT, STRING, "balanced"}},
    {"EOPSQSCRecordMinLeadM", {PERSISTENT, FLOAT, "40.0"}},
    {"EOPSQSCRecordMinQuality", {PERSISTENT, FLOAT, "0.25"}},
    {"EOPSQSCRecordMinSpeedKph", {PERSISTENT, FLOAT, "18.0"}},
    {"EOPSQSCSensitivity", {PERSISTENT, FLOAT, "1.0"}},
    {"EOPSQSCSmoothing", {PERSISTENT, FLOAT, "2.0"}},
    {"EOPSQSCUseLearnedSpeed", {PERSISTENT, BOOL, "1"}},
    {"EOPSafetyDriverTorqueThreshold", {PERSISTENT, INT, "200"}},
    {"EOPSafetyEventLogEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPSafetyEventLogPath", {PERSISTENT, STRING, "/data/safety_violations.log"}},
    {"EOPSafetyHeartbeatTimeout", {PERSISTENT, INT, "200"}},
    {"EOPSafetyMaxAccel", {PERSISTENT, INT, "340"}},
    {"EOPSafetyMaxAngleError", {PERSISTENT, INT, "240"}},
    {"EOPSafetyMaxSteeringAngle", {PERSISTENT, INT, "2700"}},
    {"EOPSafetyMaxSteeringRate", {PERSISTENT, INT, "200"}},
    {"EOPSafetyMessageTimeout", {PERSISTENT, INT, "1200"}},
    {"EOPSafetyMinAccel", {PERSISTENT, INT, "312"}},
    {"EOPShockDepthM", {PERSISTENT, FLOAT, "0.08"}},
    {"EOPShockDetection", {PERSISTENT, BOOL, "1"}},
    {"EOPShockDuration", {PERSISTENT, INT, "3"}},
    {"EOPShockHeightM", {PERSISTENT, FLOAT, "0.05"}},
    {"EOPShockSpeedLimit", {PERSISTENT, INT, "15"}},
    {"EOPShockThreshold", {PERSISTENT, FLOAT, "2.5"}},
    {"EOPSideCameraHeight", {PERSISTENT, INT, "720"}},
    {"EOPSideCameraWidth", {PERSISTENT, INT, "1280"}},
    {"EOPSideCamerasEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPSideCamerasSwapped", {PERSISTENT, BOOL, "0"}},
    {"EOPSideEGPUMode", {PERSISTENT, STRING, "off"}},
    {"EOPSideSegEGPUMode", {PERSISTENT, STRING, "off"}},
    {"EOPSimPlatform", {PERSISTENT, STRING, "rk3588"}},
    {"EOPSimScenario", {PERSISTENT, STRING, ""}},
    {"EOPSimWeather", {PERSISTENT, STRING, ""}},
    {"EOPSpeedLimitOffset", {PERSISTENT, INT, "0"}},
    {"EOPStandardFollow", {PERSISTENT, FLOAT, "1.45"}},
    {"EOPStandardJerk", {PERSISTENT, FLOAT, "1.0"}},
    {"EOPStereoEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPSubscriptionCheckInterval", {PERSISTENT, INT, "30"}},
    {"EOPSubscriptionDeviceId", {PERSISTENT, STRING, ""}},
    {"EOPSubscriptionExpiry", {PERSISTENT, STRING, ""}},
    {"EOPSubscriptionSignature", {PERSISTENT | DONT_LOG, STRING, ""}},
    {"EOPSubscriptionSkipVerify", {PERSISTENT, BOOL, "0"}},
    {"EOPSubscriptionTier", {PERSISTENT, STRING, "none"}},
    {"EOPSubscriptionToken", {PERSISTENT | DONT_LOG, STRING, ""}},
    {"EOPSurfaceEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPSurfaceGridRange", {PERSISTENT, FLOAT, "60.0"}},
    {"EOPSurfaceGridResolution", {PERSISTENT, FLOAT, "0.25"}},
    {"EOPSurfaceGridWidth", {PERSISTENT, FLOAT, "30.0"}},
    {"EOPSurfaceLongHorizon", {PERSISTENT, BOOL, "1"}},
    {"EOPSurfaceLongRange", {PERSISTENT, FLOAT, "100.0"}},
    {"EOPTJAEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPTJAMaxHoldMinutes", {PERSISTENT, INT, "10"}},
    {"EOPTLSCEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPTSCTargetLatAccel", {PERSISTENT, FLOAT, "1.8"}},
    {"EOPTSCTargetLatAccelMedium", {PERSISTENT, FLOAT, "1.8"}},
    {"EOPTSCTargetLatAccelMild", {PERSISTENT, FLOAT, "2.0"}},
    {"EOPTSCTargetLatAccelSharp", {PERSISTENT, FLOAT, "1.5"}},
    {"EOPTTSAlertsEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPTTSVoice", {PERSISTENT, STRING, "auto"}},
    {"EOPTTSVolume", {PERSISTENT, FLOAT, "1.0"}},
    {"EOPTeleEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPTeleHDR", {PERSISTENT, STRING, "hdr4"}},
    {"EOPTileLastUpdate", {PERSISTENT, INT, "0"}},
    {"EOPTouchEventNode", {PERSISTENT, STRING, ""}},
    {"EOPTrackEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPTrafficFollow", {PERSISTENT, FLOAT, "1.35"}},
    {"EOPTrafficJerk", {PERSISTENT, FLOAT, "0.8"}},
    {"EOPTripAStartDistance", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripAStartTime", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripBStartDistance", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripBStartTime", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripCurrentEngagementRatio", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripLastDistance", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripLastDuration", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripLastMaxAccel", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripLastOverrideFreeDistance", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripLastPersonalityTime", {PERSISTENT, STRING, ""}},
    {"EOPTripLifetimeEngagementRatio", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripMode", {PERSISTENT, INT, "0"}},
    {"EOPTripTotalDistance", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripTotalDrives", {PERSISTENT, INT, "0"}},
    {"EOPTripUptimeEngaged", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPUIBrightness", {PERSISTENT, INT, "0"}},
    {"EOPUIDisplayMode", {PERSISTENT, BOOL, "0"}},
    {"EOPUIHideHudSpeedKph", {PERSISTENT, INT, "0"}},
    {"EOPUIRadarTracks", {PERSISTENT, BOOL, "0"}},
    {"EOPUIRainbow", {PERSISTENT, BOOL, "0"}},
    {"EOPUploadCurrentHeaders", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPUploadCurrentId", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPUploadCurrentPath", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPUploadCurrentProgress", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPUploadCurrentSize", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPUploadCurrentUrl", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPVTSCEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPValhallaUrl", {PERSISTENT, STRING, ""}},
    {"EOPVehicleType", {PERSISTENT, STRING, "SUV_C"}},
    {"EOPWideHDR", {PERSISTENT, STRING, "hdr4"}},
    {"EOPFrontRoadSegEGPUMode", {PERSISTENT, STRING, "off"}},
    {"EOPFrontWideSegEGPUMode", {PERSISTENT, STRING, "off"}},
    {"FactoryCalibrationParams", {PERSISTENT, BYTES}},
    {"CarMake", {PERSISTENT, STRING}},
    {"CarType", {PERSISTENT, STRING}},
    {"CarVin", {PERSISTENT, STRING}},
    // ASM2464PD / Chestnut eGPU driving path (mirrors upstream UsbGpu*; named
    // Egpu* to cover both our own flashed firmware and comma's Chestnut
    // firmware on the same physical chip).
    {"EgpuDrivingEnabled", {PERSISTENT, BOOL, "0"}},
    {"EgpuDrivingLoading", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EgpuDrivingActive", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"ChestnutDrivingEnabled", {PERSISTENT, BOOL, "0"}},
    {"ChestnutDrivingLoading", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"ChestnutDrivingActive", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"CurrentMCAPRoute", {CLEAR_ON_MANAGER_START, STRING}},
    {"EOPVoiceEnabled", {PERSISTENT, BOOL}},
    {"LastGPSAltitude", {PERSISTENT, STRING}},
    {"LastGPSLatitude", {PERSISTENT, STRING}},
    {"LastGPSLongitude", {PERSISTENT, STRING}},
    // BRSC: Bumpy Road Speed Controller — shared across EOP10/NGP10/EDP10 via
    // nagaspilot/controls/ngp_brsc.py; NGP prefix (not EOP) marks features
    // ported verbatim across all three branches. See docs/eop/03_Software/Controllers/BRSC.md
    {"ngp_lon_brsc", {PERSISTENT, BOOL, "1"}},
    {"NavPilotOAuthEmail", {PERSISTENT | DONT_LOG, STRING}},
    {"NavPilotOAuthToken", {PERSISTENT | DONT_LOG, STRING}},
    {"OpenBLTFirmwareVersion", {PERSISTENT, STRING}},
    {"OpenBLTState", {CLEAR_ON_MANAGER_START, STRING, "idle"}},
    {"OpenBLTUpdateAvailable", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"UbloxAssistNowToken", {PERSISTENT | DONT_LOG, STRING}},
    {"NavDestination", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"NavDestinationWaypoints", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"NeuralNetworkLateralControl", {PERSISTENT, BOOL, "0"}},
    {"SpeedLimitPolicy", {PERSISTENT, INT, "4"}},
    {"SteamDAuthToken", {PERSISTENT | DONT_LOG, STRING, ""}},
    {"SteamDControlRequest", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"SteamDEnabled", {PERSISTENT, BOOL, "0"}},
    {"SteamDGeofencePolygon", {PERSISTENT, STRING, ""}},
    {"SteamDJoystickInput", {PERSISTENT, BOOL, "1"}},
    {"SteamDRemoteControl", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL, "0"}},
};
