"""EOP params that are deliberately not settings controls.

Every `EOP*` key in `common/params_keys.h` must be either in descriptor.py or
here with a reason -- test_params_coverage.py enforces exactly that, so a param
can never go missing from the UI silently. It can only go missing *loudly*, by
someone adding it here.

TRIAGED holds keys with a real reason. UNTRIAGED is the honest bucket: keys
inherited from the C++ panel's coverage gap that nobody has classified yet. It
is expected to shrink to empty, and the test prints its size on every run so
the debt stays visible rather than becoming permanent.
"""

from __future__ import annotations

# key -> why it is not a user-facing setting
TRIAGED: dict[str, str] = {}

# Not yet classified. Populated from the current gap so the gate is meaningful
# from day one; entries move to TRIAGED (with a reason) or into descriptor.py.
UNTRIAGED: set[str] = {
  "EOPALCCAllowAlways",
  "EOPALCCHoldAtStandstill",
  "EOPALCCSteeringModeOnBrake",
  "EOPALCCUnifiedEngagement",
  "EOPAccelerationProfile",
  "EOPAdaptdEnabled",
  "EOPAdaptiveGapEnabled",
  "EOPAggressiveFollow",
  "EOPAggressiveJerk",
  "EOPBSDEnabled",
  "EOPBSDMinSpeed",
  "EOPBluetoothCANInterface",
  "EOPBluetoothEnabled",
  "EOPBluetoothPairWindow",
  "EOPBluetoothRadarEnabled",
  "EOPCATEnabled",
  "EOPCATManualSR",
  "EOPCATPersist",
  "EOPCurrentRegion",
  "EOPCurveSpeedDBPath",
  "EOPCurveSpeedLearnEnabled",
  "EOPDLONCurvesEnabled",
  "EOPDLONForceStopsEnabled",
  "EOPDLONLaneConfidenceEnabled",
  "EOPDLONLowSpeedEnabled",
  "EOPDLONNavigationEnabled",
  "EOPDLONSignalEnabled",
  "EOPDLONSlowLeadEnabled",
  "EOPDLONSpeedLimitEnabled",
  "EOPDLONStopPredictionEnabled",
  "EOPDLPCurvesEnabled",
  "EOPDeviceBeep",
  "EOPDeviceGoOffRoad",
  "EOPDeviceIsRhd",
  "EOPDeviceModelList",
  "EOPDeviceModelSelected",
  "EOPDeviceName",
  "EOPFactoryCalibrated",
  "EOPFeatureAdvancedAnalytics",
  "EOPFeatureAiRouting",
  "EOPFeatureCloudBackup",
  "EOPFeatureCrossDeviceSync",
  "EOPFeatureDrivingScore",
  "EOPFeatureEmergencyAlert",
  "EOPFeatureFleetMode",
  "EOPFeatureLiveLocationShare",
  "EOPFeatureLiveTraffic",
  "EOPFeatureObdDashboard",
  "EOPFeaturePriorityTiles",
  "EOPFeatureRemoteCamera",
  "EOPFeatureRouteReplay",
  "EOPFeatureTelemetry",
  "EOPFeatureTripSync",
  "EOPFollowingDistance",
  "EOPFrontRoadSegEGPUMode",
  "EOPFrontWideSegEGPUMode",
  "EOPGridEnabled",
  "EOPGroundEnabled",
  "EOPHealthMonitorEnabled",
  "EOPHybridPlannerEnabled",
  "EOPIgnitionOn",
  "EOPLCABSMEnabled",
  "EOPLCAConfirmRequired",
  "EOPLCAControllerEnabled",
  "EOPLCAGapEvalEnabled",
  "EOPLCALaneWidthEnabled",
  "EOPLCASurroundOverride",
  "EOPLCAdjacentLeadHandoff",
  "EOPLanguage",
  "EOPLatALCC",
  "EOPLatRoadEdgeDetection",
  "EOPLeftCameraEnabled",
  "EOPLonExtRadar",
  "EOPMSLCAlert",
  "EOPMSLCEnabled",
  "EOPMSLCOffsetFixed",
  "EOPMSLCOffsetPercent",
  "EOPMTSCEnabled",
  "EOPMapdEnabled",
  "EOPMicAdaptiveLoudness",
  "EOPMultiCameraCalibEnabled",
  "EOPNSLCEnabled",
  "EOPNavEnabled",
  "EOPNavPilotAddress",
  "EOPNavPilotPaired",
  "EOPNavVoiceEnabled",
  "EOPOsmLocalizerEnabled",
  "EOPParkingMode",
  "EOPPredictEnabled",
  "EOPRearCameraHeight",
  "EOPRearCameraWidth",
  "EOPRearEGPUMode",
  "EOPRearSegEGPUMode",
  "EOPRecordSnap",
  "EOPRecorddImpactSensitivity",
  "EOPRecorddParkingEnabled",
  "EOPRecorddParkingHours",
  "EOPRecorddPostBufferSec",
  "EOPRecorddPreBufferSec",
  "EOPRecorddQuality",
  "EOPRecorddSnapAutoG",
  "EOPRecorddSnapImuMs",
  "EOPRedControllerEnabled",
  "EOPRelaxedFollow",
  "EOPRelaxedJerk",
  "EOPRightCameraEnabled",
  "EOPRoadHDR",
  "EOPSGMMapPath",
  "EOPSLCConfirmHigher",
  "EOPSLCConfirmLower",
  "EOPSLCOffset1",
  "EOPSLCOffset2",
  "EOPSLCOffset3",
  "EOPSLCOffset4",
  "EOPSLCOffset5",
  "EOPSLCOffset6",
  "EOPSLCOffset7",
  "EOPSOCControllerEnabled",
  "EOPSPPAutoReconnect",
  "EOPSPPChannel",
  "EOPSPPDeviceName",
  "EOPSPPEnabled",
  "EOPSPPMaxClients",
  "EOPSPPPairedDevice",
  "EOPSPPRpcRequest",
  "EOPSPPRpcResponse",
  "EOPSQSCEnabled",
  "EOPSQSCLookaheadEnabled",
  "EOPSQSCProfile",
  "EOPSQSCRecordMinLeadM",
  "EOPSQSCRecordMinQuality",
  "EOPSQSCRecordMinSpeedKph",
  "EOPSQSCSensitivity",
  "EOPSQSCSmoothing",
  "EOPSQSCUseLearnedSpeed",
  "EOPSafetyDriverTorqueThreshold",
  "EOPSafetyEventLogEnabled",
  "EOPSafetyEventLogPath",
  "EOPSafetyHeartbeatTimeout",
  "EOPSafetyMaxAccel",
  "EOPSafetyMaxAngleError",
  "EOPSafetyMaxSteeringAngle",
  "EOPSafetyMaxSteeringRate",
  "EOPSafetyMessageTimeout",
  "EOPSafetyMinAccel",
  "EOPShockDepthM",
  "EOPShockDetection",
  "EOPShockDuration",
  "EOPShockHeightM",
  "EOPShockSpeedLimit",
  "EOPShockThreshold",
  "EOPSideCameraHeight",
  "EOPSideCameraWidth",
  "EOPSideCamerasEnabled",
  "EOPSideCamerasSwapped",
  "EOPSideEGPUMode",
  "EOPSideSegEGPUMode",
  "EOPSimPlatform",
  "EOPSimScenario",
  "EOPSimWeather",
  "EOPSpeedLimitOffset",
  "EOPStandardFollow",
  "EOPStandardJerk",
  "EOPStereoEnabled",
  "EOPSubscriptionCheckInterval",
  "EOPSubscriptionDeviceId",
  "EOPSubscriptionExpiry",
  "EOPSubscriptionSignature",
  "EOPSubscriptionSkipVerify",
  "EOPSubscriptionTier",
  "EOPSubscriptionToken",
  "EOPSurfaceEnabled",
  "EOPSurfaceLongRange",
  "EOPTJAEnabled",
  "EOPTJAMaxHoldMinutes",
  "EOPTLSCEnabled",
  "EOPTSCTargetLatAccelMedium",
  "EOPTSCTargetLatAccelMild",
  "EOPTSCTargetLatAccelSharp",
  "EOPTTSAlertsEnabled",
  "EOPTTSVoice",
  "EOPTTSVolume",
  "EOPTeleEnabled",
  "EOPTeleHDR",
  "EOPTileLastUpdate",
  "EOPTouchEventNode",
  "EOPTrackEnabled",
  "EOPTrafficFollow",
  "EOPTrafficJerk",
  "EOPTripAStartDistance",
  "EOPTripAStartTime",
  "EOPTripBStartDistance",
  "EOPTripBStartTime",
  "EOPTripCurrentEngagementRatio",
  "EOPTripLastDistance",
  "EOPTripLastDuration",
  "EOPTripLastMaxAccel",
  "EOPTripLastOverrideFreeDistance",
  "EOPTripLastPersonalityTime",
  "EOPTripLifetimeEngagementRatio",
  "EOPTripMode",
  "EOPTripTotalDistance",
  "EOPTripTotalDrives",
  "EOPTripUptimeEngaged",
  "EOPTripUptimeOnroad",
  "EOPUIBrightness",
  "EOPUIDisplayMode",
  "EOPUIRadarTracks",
  "EOPUIRainbow",
  "EOPUploadCurrentHeaders",
  "EOPUploadCurrentId",
  "EOPUploadCurrentPath",
  "EOPUploadCurrentProgress",
  "EOPUploadCurrentSize",
  "EOPUploadCurrentUrl",
  "EOPVTSCEnabled",
  "EOPValhallaUrl",
  "EOPVehicleType",
  "EOPWideHDR",
}


def excluded_keys() -> frozenset[str]:
  return frozenset(TRIAGED) | frozenset(UNTRIAGED)
